[package]
name = "jvm-class-proto"
description = "Utilities for implementing Java classes in Rust"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
dyn-clone = { workspace = true }

jvm-types = { workspace = true }
jvm = { workspace = true }
